# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm test
    - run: npm run build
    - run: cp -r /home/webmydi/app/actions-runner/webapp/webapp/webapp/* /home/webmydi/app
    - run: cp -r /home/webmydi/app/actions-runner/webapp/webapp/webapp/.next/* /home/webmydi/app/.next
    - run: rm -f -r /home/webmydi/app/_next
    - run: mkdir -p /home/webmydi/app/_next/static
    - run: cp -r /home/webmydi/app/actions-runner/webapp/webapp/webapp/.next/static/* /home/webmydi/app/_next/static
   # - run: yarn --cwd /home/webmydi/app run build 
   # - run: pm2 restart nextjs
    

